---
title: "Authors"
---

**Suggested Citation Style:** Platt, A. (2024, October 8). *Design and analysis of preference trials in mental health research* [Conference presentation]. Duke Global Mental Health Conference 2024, Durham, NC, United States.

Platt, A. Design and analysis of preference trials in mental health research.

Gallis, J. Design and analysis of individually randomized group treatment trials in mental health research.

Kenny, A. Time-varying treatment effects in mental health research.

Patel, M., Rauh, C., Premasinghe, I., & Stafford, A. M. An Academic-Community Partnership to Address Inequities in Depression among Latino/a/e Adolescents in North Carolina.

Akinrinde, D., Ayeni, S., Akande, D., & Adegbite, O. Effect of a school-based resilience training program on the psychosocial health outcomes of vulnerable adolescents in Oyo State, Nigeria.

Dow, D., Rahim, F., Shayo, A., Baumgartner, J. N., Nasuwa, F., Senkoro, E., McGann, K., Dougherty, J., Gallis, J., O'Donnell, K., & Mmbaga, B. Addressing the Global Mental Health Care Gap for Adolescents Living with HIV: Transferrable Lessons South to North.

Ochieng, Y. A., Ashita, N., Rono, W., Njuguna, C., Owino, L., Midiwo, N., Ayaye, E., Kadima, S., Mokeira, S., Wanyama, M. S., Saina, D. C., Bonner, M., Njuguna, F., & Puffer, E. S. Empowering Families Coping with Pediatric Sickle Cell Disease in Kenya: A Qualitative Study to Inform a Multi-Level Psychosocial Intervention.

Staton, C. A., Vissoci, J. R. N., Phillips, A. J., Buono, M., Perez de Souza, J. V., Minja, L., Gallis, J. A., Santos, P. C. P., Boshe, J., Madundo, K., Sakita, F., & Mmbaga, B. T. Effectiveness of a Brief Negotiational Intervention and Text-Based Booster to Reduce Harmful and Hazardous Alcohol Use in the Emergency Department of a Low-Resource Setting: A Pragmatic Randomized Adaptive Clinical Trial in Moshi, Tanzania.

Staton, C. A., Vissoci, J. R. N., Phillips, A. J., Gamassa, E., Sakita, F., & Mmbaga, B. T. PRICE-Alcohol: Planning the Regional Implementation of a Culturally Adapted Brief Intervention for Alcohol for Tanzanian Emergency Departments.

Staton, C. A., Vissoci, J. R. N., Phillips, A. J., Buono, M., Pesambili, M., Mwita, W., Emanuel, F., O’Leary, P., & Knettel, B. Exploring the Mediating Effects of Depression on the Effectiveness of a Brief Negotiational Intervention in Reducing Harmful Alcohol Use in Moshi, Tanzania: A Mixed Method Study.

Staton, C. A., Buono, M., Pauley, A., West, K., Mikindo, M., Sawe, Y., Kilasara, J., Rent, S., Mchome, B., Sakita, F., & Mmbaga, B. T. The Burden of Generational Harm due to Alcohol use in Tanzania: a mixed method study of pregnant women.

Reif, S., Wilson, S., Wilson, E., & Davis, B. Community informed adaptation and implementation of a mental health and substance use screening and referral process in HIV Pre-exposure Prophylaxis (PrEP) care in the US Deep South.

Hunter, G., Parnell, H., Andrews, A., Briley, D., Whetten, K., & Lansford, J. Implementing positive youth development and sexuality education to address health disparities in rural North Carolina.

Weyer Johnson, L., Purnell, C., Yac, J., Lopez, O., Orellana, R., Merida, B., & Davis, D. Mental Health of Indigenous Gay and Bisexual Men in Guatemala: a qualitative study.

Merritt, J. Enhancing Peer Support in Medical Spaces for Substance Dependency and Harm Reduction Among LGBTQIA+ Individuals in the South.

Baziyants, G. A., Dodge, K. A., Goodman, W. B., Bai, Y., Murphy, R. A., & O'Donnell, K. Promoting Long-Term Parent and Caregiver Mental Health Through Universal Postnatal Nurse Home Visiting.

Shartle, K., Maselko, J., Escobar Carias, M. S., & Baranov, V. Does prior maternal adversity exacerbate the mental health effects of external shocks? Evidence from mothers and children in rural Pakistan.

Zanatti, R., Salm, M. F., Alcantar Magana, A., Puffer, E. S., & Nagy, G. Coping Together, a Brief Family-Based Intervention, for Latinx Immigrants and the Importance of Community-Defined Adaptations of Mental Health Interventions.

Kuniyoshi de Lara, D., Teixeira, T. M., Nascimento de Oliveira, N., Pereira, N. D., & Fleig Dal Forno, L. Challenges in inclusive education for students with autism: The critical role of family engagement in a southern Brazilian city.
