---
title: "Duke Global Mental Health Conference 2024"
subtitle: "Building a Global Mental Health Community: Research, Policy, and Practice Across Disciplines"
---

The [Duke Center for Global Mental Health](https://globalhealth.duke.edu/center-global-mental-health) is excited to invite you to our first Duke Global Mental Health Conference on October 8, 2024, located on the Trent Semans Center 6th floor. Our theme is: Building a Global Mental Health Community: Research, Policy, and Practice Across Disciplines. This one-day event will bring together leaders, researchers, practitioners, and advocates from the Duke community and our partners around the world to share our work and ideas for working together.

## Key Details

|             |                                                                                                                 |     |
|----------------|----------------------|----------------------------------|
| **When**    | October 8, 2024, 8:30am-5:00pm                                                                                  |     |
| **Where**   | Trent Semans Center (6th floor) and virtual                                                                     |     |
| **Parking** | [Directions](https://globalhealth.duke.edu/sites/default/files/event-attachments/directions-trent_semans_1.pdf) |     |
| **Zoom**    | See schedule                                                                                                |     |

## Register

Please register [here](https://globalhealth.duke.edu/events/2024-duke-global-mental-health-conference). This is a hybrid event. In-person registration closed Oct 3. Virtual registration is open until Oct 6.

## Share

Use the hastag #dukegmh to share your experience on social media.
