---
title: "Sessions"
---

## Global Mental Health at Duke: Achievements and Opportunities

The opening session will welcome participants and introduce the Duke Center for Global Mental Health. The Center serves as a hub for interdisciplinary collaboration, connecting faculty and researchers at Duke who are focused on addressing global and local mental health disparities. Attendees will learn about the Center’s commitment to integrating mental health across diverse fields such as psychology, psychiatry, policy, and public health. The session will highlight both the Center’s research and training initiatives and the opportunities for collaboration within the global mental health community at Duke.

+:----------+
| [Eve Puffer](https://sites.globalhealth.duke.edu/evepuffer/), Director, Duke Center for Global Mental Health (DCGMH) |
+------+
| [Maeve Salm](https://globalhealth.duke.edu/people/salm-maeve), Clinical Research Coordinator, DCGMH |
+------+

## Panel: Perspectives From our Community; Research, Practice, and Policy in Global Mental Health

This panel will feature diverse insights from leaders across Duke and beyond. Speakers from the Duke Center for Global Mental Health, Sanford School of Public Policy, Duke Global Health Innovation Center, El Futuro, and Duke Population Health Sciences will share their unique approaches to addressing mental health challenges. The discussion will explore how research, policy, and community-based practices intersect to improve mental health care both locally and globally. 

+:----------+
| Moderator: [Brandon Knettel](https://globalhealth.duke.edu/people/knettel-brandon), Associate Director, DCGMH |
+------+
| Panelist: [Kate Whetten](https://globalhealth.duke.edu/people/whetten-kathryn), Sanford School of Public Policy |
+------+
| Panelist: [Krishna Udayakumar](https://dukeghic.org/people/krishna-udayakumar/), Duke Global Health Innovation Center |
+------+
| Panelist: [Luke Smith](https://elfuturo-nc.org/people/david-lucas-luke-smith/), El Futuro |
+------+
| Panelist: [Charles Muiruri](https://globalhealth.duke.edu/people/muiruri-charles), Population Health Sciences |
+------+

## Faculty Research Spotlights

This conference session will spotlight the innovative work of faculty members from the Center for Health Policy and Inequalities Research, Department of Romance Studies, School of Nursing, Department of Sociology, and Church World Service. Presentations will cover a range of global topics, including trauma interventions for orphaned children in Kenya, the development of outpatient psychiatry in Haiti, therapeutic storytelling with diverse newcomer communities, and the impact of differences in clergy practices. Together, these talks will provide valuable insights into the intersections of culture, mental health, and healing across various global contexts.

| Presenter | Title |
|:--   |:--      |
| [Christine Gray](https://globalhealth.duke.edu/people/gray-christine), DGHI, Center for Health Policy and Inequalities Research | Addressing trauma in orphaned children in Kenya: From descriptive epidemiology to implementation science | 
| [Deborah Jenson](https://sites.fhi.duke.edu/healthhumanitieslab/team/deborah-jenson/), Department of Romance Studies | The birth of outpatient psychiatry in Louis Mars’ Haiti: Utopia and dystopia |
| [Irene Felsman](https://globalhealth.duke.edu/people/felsman-irene), Duke University School of Nursing and [Thakur Mishra](https://cwsglobal.org/), Church World Service, Refugee Wellness Program Manager | Therapeutic storytelling with culturally diverse newcomer communities |
| [David Eagle](https://globalhealth.duke.edu/people/eagle-david), Department of Sociology | When does difference do damage? Evidence from a study of clergy |

## Research Symposia Round 1

### Features and challenges in the design and analysis of trials in global mental health research

When evaluating interventions and programs in mental health research, a vast range of different trial designs are available. The final choice of design is based on a variety of factors including, but not limited to the nature of the intervention being evaluated, the research context, the primary research question and logistical and other related considerations. In this symposium, we will use ongoing and completed mental health studies to highlight features and challenges in several trial designs, including preference trials, individually-randomized group treatment trials and stepped wedge trials with the goal to engage in a discussion with the audience around what important features to pay attention to when designing such trials.

Chair and Discussant: [Elizabeth ("Liz") Turner](https://globalhealth.duke.edu/people/turner-elizabeth), Associate Professor of Biostatistics & Global Health, Department of Biostatistics & Bioinformatics and DGHI

| Title | Presenter | Abstract |
|:--   |:--      |:--       |
| Design and analysis of preference trials in mental health research | [Alyssa Platt](https://globalhealth.duke.edu/people/platt-alyssa), Department of Biostatistics & Bioinformatics and DGHI | [Link](abstracts.html#design-and-analysis-of-preference-trials-in-mental-health-research) |
| Design and analysis of individually randomized group treatment trials in mental health research | [John Gallis](https://globalhealth.duke.edu/people/gallis-john), Department of Biostatistics & Bioinformatics and DGHI | [Link](abstracts.html#design-and-analysis-of-individually-randomized-group-treatment-trials-in-mental-health-research) |
| Time-varying treatment effects in mental health research | [Avi Kenny](https://globalhealth.duke.edu/people/kenny-avi), Department of Biostatistics & Bioinformatics and DGHI | [Link](abstracts.html#time-varying-treatment-effects-in-mental-health-research) |

### Centering adolescent mental health: Intervention research to maximize resonance and impact

Maeve Abstract

Chair and Discussant:

| Title | Presenter | Abstract |
|:--   |:--      |:--       |
| | | 

### Understanding alcohol use and harm-reduction interventions in Northern Tanzania

Maeve Abstract

Chair and Discussant:

| Title | Presenter | Abstract |
|:--   |:--      |:--       |
| | |

## Research Symposia Round 2

### Addressing mental health in the community: Implementation of research and practice from the Southern US to the Global South

Maeve Abstract

Chair and Discussant:

| Title | Presenter | Abstract |
|:--   |:--      |:--       |
| | |

### Child and caregiver mental health: Global perspectives on risk and resilience

Maeve Abstract

Chair and Discussant:

| Title | Presenter | Abstract |
|:--   |:--      |:--       |
| | |
