---
title: "Symposia Round 1"
---

**1:30-2:30pm**

Choose from 1 of 3 of the following concurrent sessions.

## Features and challenges in the design and analysis of trials in global mental health research

**6th floor** ([Video](https://duke.zoom.us/rec/share/L8mcwDank8aNTEKfFiqjyJDYTYoPoBK3vRTsNNh0bvCvH97skktES9ubue2AExbk.fgkxWll6bDYYbjFG))

When evaluating interventions and programs in mental health research, a vast range of different trial designs are available. The final choice of design is based on a variety of factors including, but not limited to the nature of the intervention being evaluated, the research context, the primary research question and logistical and other related considerations. In this symposium, we will use ongoing and completed mental health studies to highlight features and challenges in several trial designs, including preference trials, individually-randomized group treatment trials and stepped wedge trials with the goal to engage in a discussion with the audience around what important features to pay attention to when designing such trials.

Chair and Discussant: [Elizabeth ("Liz") Turner](https://globalhealth.duke.edu/people/turner-elizabeth), Associate Professor of Biostatistics & Global Health, Department of Biostatistics & Bioinformatics and DGHI

| Title                                                                                           | Presenter    |
|:-----------------------------------|:-----------------------------------|
| Design and analysis of preference trials in mental health research                              | Alyssa Platt |
| Design and analysis of individually randomized group treatment trials in mental health research | John Gallis  |
| Time-varying treatment effects in mental health research                                        | Avi Kenny    |
| Addressing the Global Mental Health Care Gap for Adolescents Living with HIV: Transferrable Lessons South to North                            | Dorothy Dow                                            |

: {tbl-colwidths="[75, 25]"}

## Centering adolescent mental health: Intervention research to maximize resonance and impact

**4th floor, Classroom 4067** ([video](https://duke.zoom.us/rec/share/4Ec4KcHPjLtUTle2nui8XI2Bn3bi1SgnuScNeP9SAD0klX9uqlRhCgm_Ru2DR3O7.runC2QE676B3_FxX))

This symposium features three talks addressing mental health challenges among vulnerable adolescents in different global contexts. The first presentation discusses an academic-community partnership in North Carolina to improve depression treatment for Latino/a/e adolescents by developing culturally appropriate training modules for healthcare providers. The second talk evaluates a school-based resilience program in Nigeria, showing reductions in anxiety and depression among vulnerable adolescents. The third presentation explores the mental health care gap for adolescents living with HIV in Tanzania and the U.S., highlighting peer-led interventions and lessons from low-income settings that could be adapted for higher-income contexts.

Chair and Discussant: [Allison McCord Stafford](https://medschool.duke.edu/profile/allison-stafford), Assistant Professor, Duke University School of Nursing

| Title                                                                                                                                         | Presenter                                              |
|:-----------------------------------|:-----------------------------------|
| An Academic-Community Partnership to Address Inequities in Depression among Latino/a/e Adolescents in North Carolina                          | Milani Patel, Carmen Rauh, and Allison McCord Stafford |
| Effect of a school-based resilience training program on the psychosocial health outcomes of vulnerable adolescents in Oyo State, Nigeria      | Akinrinde Deborah                                      |
| Intergenerational childhood trauma: patterns by subtype across two generations in a longitudinal Barbados cohort | Rebecca S. Hock |
| Empowering Families Coping with Pediatric Sickle Cell Disease in Kenya: A Qualitative Study to Inform a Multi-Level Psychosocial Intervention | Yvonne A. Ochieng                                      |


: {tbl-colwidths="[75, 25]"}

## Understanding alcohol use and harm-reduction interventions in Northern Tanzania

**4th floor, Classroom 4030** ([video](https://duke.zoom.us/rec/share/UiKx7OGY5E5jd7t3C3P5txAjcE9LuBbL6vYp69QiW9jrBfx9Tei7VD8C7qPb6g8v.Q74gtAkITEj25jPL))

This symposium presents four talks addressing alcohol use and its associated health impacts in Tanzania. The first study evaluates a brief negotiational intervention with mobile health boosters, showing significant reductions in harmful alcohol use among emergency department patients. The second talk outlines a plan to implement this intervention regionally, adapting it to local contexts. The third study explores the relationship between depression and alcohol use, finding no mediation effect of depression but suggesting the intervention may improve both conditions over time. The final presentation highlights the growing issue of prenatal alcohol use in Tanzania, emphasizing the need for community education and pre-pregnancy interventions to address fetal alcohol spectrum disorders.

Chair: [Catherine A. Staton](https://globalhealth.duke.edu/people/staton-catherine), Professor, Global Emergency Medicine Innovation and Implementation (GEMINI) Research Center

Discussant: [Joao Ricardo Nickenig Vissoci](https://globalhealth.duke.edu/people/vissoci-joao-ricardo), Assistant Professor, GEMINI

| Title                                                                                                                                                                                                                                           | Presenter                  |
|:-----------------------------------|:-----------------------------------|
| Effectiveness of a Brief Negotiational Intervention and Text-Based Booster to Reduce Harmful and Hazardous Alcohol Use in the Emergency Department of a Low-Resource Setting: A Pragmatic Randomized Adaptive Clinical Trial in Moshi, Tanzania | ⁠Kim Madundo                |
| PRICE-Alcohol: Planning the Regional Implementation of a Culturally Adapted Brief Intervention for Alcohol for Tanzanian Emergency Departments                                                                                                  | ⁠⁠Ashley Phillips            |
| Exploring the Mediating Effects of Depression on the Effectiveness of a Brief Negotiational Intervention in Reducing Harmful Alcohol Use in Moshi, Tanzania: A Mixed Method Study                                                               | ⁠⁠Mia Buono & Winfrida Mwita |
| The Burden of Generational Harm due to Alcohol use in Tanzania: a mixed method study of pregnant women                                                                                                                                          | ⁠⁠Alena Pauley               |

: {tbl-colwidths="[75, 25]"}
